Repository PTIT-D22KH/milktea_sales_management_project, pull requests merged in 2024-09, with the labels that each got.

#1 Add project structures to run in Netbeans
  .gitignore
  bin/README.md
  nbproject/project.properties
  pom.xml
  src/main/java/controllers/README.md
  src/main/java/dao/README.md
  src/main/java/main/Main.java
  src/main/java/main/README.md
  src/main/java/models/README.md
  src/main/java/utils/README.md
  src/main/java/views/README.md
  src/main/resources/database/README.md
  src/main/resources/icons/README.md
  src/main/resources/images/README.md
  src/test/java/README.md
  src/test/java/controllers/README.md
  src/test/java/dao/README.md
  src/test/java/main/MainTest.java
  src/test/java/main/README.md
  src/test/java/models/README.md
  src/test/java/utils/README.md
  src/test/java/views/README.md
Labels: enhancement, restructure

#2 Add model.java
  src/main/java/models/Model.java
Labels: enhancement

#3 Add Employee and FoodCategory models
  src/main/java/models/Employee.java
  src/main/java/models/FoodCategory.java
Labels: enhancement

#7 Add Customer class, Dao interface as base class and create helper class to connect to the database, ER Diagrams
  src/main/java/controllers/README.md
  src/main/java/dao/CustomerDao.java
  src/main/java/dao/Dao.java
  src/main/java/dao/README.md
  src/main/java/main/Main.java
  src/main/java/main/README.md
  src/main/java/models/Customer.java
  src/main/java/models/README.md
  src/main/java/utils/ConfigLoader.java
  src/main/java/utils/DatabaseConnector.java
  src/main/java/utils/README.md
  src/main/java/views/README.md
  src/main/resources/database/README.md
  src/main/resources/icons/README.md
  src/main/resources/images/ERDDiagram.jpg
  src/main/resources/images/README.md
  src/main/resources/images/er_diagram.jpg
  src/test/java/controllers/README.md
  src/test/java/dao/CustomerDaoTest.java
  src/test/java/dao/README.md
  src/test/java/main/README.md
  src/test/java/models/CustomerTest.java
  src/test/java/models/README.md
  src/test/java/utils/ConfigLoaderTest.java
  src/test/java/utils/DatabaseConnectorTest.java
  src/test/java/utils/README.md
  src/test/java/views/README.md
  src/test/resources/database/README.md
  src/test/resources/icons/README.md
  src/test/resources/images/README.md
Labels: enhancement, help wanted

#9 Add shipment and table models and util classes
  src/main/java/models/Shipment.java
  src/main/java/models/Table.java
  src/main/java/utils/ShipmentStatus.java
  src/main/java/utils/TableStatus.java
Labels: enhancement

#12 Create CustomerDao class and SQL queries to create table and insert data
  .gitignore
  src/main/java/dao/CustomerDao.java
  src/main/java/dao/Dao.java
  src/main/java/main/Main.java
  src/main/java/models/Customer.java
  src/main/resources/database/create_new_table.sql
  src/main/resources/database/insert_data.sql
  src/test/java/dao/CustomerDaoTest.java
Labels: enhancement
